site_name: i think therefore i communicate 
site_url: https://s-santillan.github.io/
site_author: s-santillan
theme:
  name: material
  palette:
    primary: blue grey
    accent: indigo
  font:
    text: Noto Serif
  features:
    #    - navigation.tabs
    - navigation.path
    - navigation.indexes
markdown_extensions: 
  - attr_list
  - md_in_html
  # Didn't realize I'd need to explicitly allow markdown in html
extra_css:
  - stylesheets/custom.css
# nav:
#     - Home: 'index.md'
#     - Percolations:
#       - 'percolations/index'
