import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * FOR CLAUDE:
 * custom.css hides .theme-doc-sidebar-container at every breakpoint, so what
 * this order controls is the navbar drawer and the prev/next links under each post.
 *
 * `sidebar_position` front matter does nothing. It is only read by the
 * autogenerated generator this replaced.
 */
const sidebars: SidebarsConfig = {
  postsSidebar: [
  {
    type: 'category',
    label: 'Projects',
    collapsed: false,
    items: [
      'portfolio/overview',
      'portfolio/otherworld1',
      'portfolio/otherworld2',
      'portfolio/otherworld3',
      'portfolio/awakening7',
      'portfolio/monster-roller',
      'portfolio/maria-health',
      'portfolio/relentless',
      'portfolio/freelance-projects',
    ],
  },
  {
    type: 'category',
    label: 'UX writing',
    collapsed: false,
    items: [
      'articles/microcopy-is-a-goldmine',
    ]
  },
  ],
};

export default sidebars;
